services:
#    ap_metronic.example:
#        class: APNet\Bundle\APMetronicBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

services:
    apnetmetronic.twig.IsLoadedExtension:
        class: APNet\Bundle\APMetronicBundle\Twig\IsLoadedExtension
        tags: [{ name: twig.extension }]
        arguments:
             twig: "@twig"